// Generates public/firebase-messaging-sw.js with Firebase config injected from env vars.
// Runs automatically during `npm run build`. Run manually with `npm run gen-sw` for local dev.
import { writeFileSync, readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// Parse .env for local dev (silent fail if absent)
try {
  for (const line of readFileSync(resolve(root, '.env'), 'utf8').split('\n')) {
    const eq = line.indexOf('=')
    if (eq < 1 || line.trim().startsWith('#')) continue
    const key = line.slice(0, eq).trim()
    const val = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '')
    if (key && !process.env[key]) process.env[key] = val
  }
} catch { /* no .env */ }

const {
  VITE_FIREBASE_API_KEY:            apiKey,
  VITE_FIREBASE_AUTH_DOMAIN:        authDomain,
  VITE_FIREBASE_PROJECT_ID:         projectId,
  VITE_FIREBASE_STORAGE_BUCKET:     storageBucket,
  VITE_FIREBASE_MESSAGING_SENDER_ID: messagingSenderId,
  VITE_FIREBASE_APP_ID:             appId,
} = process.env

const out = resolve(root, 'public/firebase-messaging-sw.js')

if (!projectId) {
  writeFileSync(out, '// Firebase not configured — run `npm run gen-sw` after adding .env\n')
  console.log('[gen-sw] No Firebase config found, stub written.')
  process.exit(0)
}

writeFileSync(out, `\
// Auto-generated by scripts/gen-sw.mjs — do not edit manually
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js')

firebase.initializeApp({
  apiKey: '${apiKey}',
  authDomain: '${authDomain}',
  projectId: '${projectId}',
  storageBucket: '${storageBucket}',
  messagingSenderId: '${messagingSenderId}',
  appId: '${appId}',
})

const messaging = firebase.messaging()

messaging.onBackgroundMessage(({ notification, data }) => {
  return self.registration.showNotification(
    notification?.title ?? 'Weight Tracker',
    {
      body: notification?.body ?? '',
      icon: '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
      tag: data?.tag ?? 'weight-reminder',
      renotify: true,
      data,
    }
  )
})
`)
console.log('[gen-sw] ✓ firebase-messaging-sw.js generated')
